In [1]:
import pandas as pd
import numpy as np
import ast
import datetime
from math import radians, cos, sin, asin, sqrt

In [2]:
dtypes={
    'CALL_TYPE':'category',
    'ORIGIN_CALL':'category',
    'ORIGIN_STAND':'category',
    'TAXI_ID':'category',
    'DAY_TYPE':'category'
}

usecols = ['CALL_TYPE', 'ORIGIN_CALL', 'ORIGIN_STAND', 'TAXI_ID', 'TIMESTAMP', 'DAY_TYPE', 'MISSING_DATA', 'POLYLINE']

#df = pd.read_csv('train.csv', dtype=dtypes, usecols=usecols, skiprows=range(1, 1264770), nrows=2)
df = pd.read_csv('train.csv', dtype=dtypes, usecols=usecols)

# dropping and converting some columns
# TRIP_ID: id, DAY_TYPE: calculado errado no dataset.
#df.drop(['TRIP_ID','DAY_TYPE' ], axis=1, inplace=True)
df.TIMESTAMP = pd.to_datetime(df.TIMESTAMP, unit='s')

In [3]:
df.head(2)

,CALL_TYPE,ORIGIN_CALL,ORIGIN_STAND,TAXI_ID,TIMESTAMP,DAY_TYPE,MISSING_DATA,POLYLINE
0,C,NaN,NaN,20000589,2013-07-01 00:00:58,A,False,"[[-8.618643,41.141412],[-8.618499,41.141376],[..."
1,B,NaN,7,20000596,2013-07-01 00:08:23,A,False,"[[-8.639847,41.159826],[-8.640351,41.159871],[..."

In [4]:
def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    #dlon = lon2 - lon1 
    #dlat = lat2 - lat1 
    a = sin((lat2 - lat1)/2)**2 + cos(lat1) * cos(lat2) * sin((lon2 - lon1)/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r

In [5]:
def outliers_iqr(line):
    if line.size>0:
        q1_lon, q3_lon = np.percentile(line[:,0], [25, 75])
        iqr_lon = q3_lon - q1_lon
        lower_bound_lon = q1_lon - (iqr_lon * 1.5)
        upper_bound_lon = q3_lon + (iqr_lon * 1.5)
        

        q1_lat, q3_lat = np.percentile(line[:,1], [25, 75])
        iqr_lat = q3_lat - q1_lat
        lower_bound_lat = q1_lat - (iqr_lat * 1.5)
        upper_bound_lat = q3_lat + (iqr_lat * 1.5)
        
        # print(np.where((line[:,0] > upper_bound_lon) | (line[:,0] < lower_bound_lon))[0], '----', np.where((line[:,1] > upper_bound_lat) | (line[:,1] < lower_bound_lat))[0], '-----', final)
       
        return np.unique(np.concatenate([np.where((line[:,0] > upper_bound_lon) | (line[:,0] < lower_bound_lon))[0], \
                                         np.where((line[:,1] > upper_bound_lat) | (line[:,1] < lower_bound_lat))[0]], axis=0))

In [6]:
def converte_dots_b(x):
    
    global cont;
    
    try:
        cont+=1
        dist=0
        line = np.array(ast.literal_eval(x))
       
        #print(list(set(outliers)))
        if len(line) > 0:
            line=np.delete(line,list(outliers_iqr(line)), 0)
            
        for index,_ in enumerate(line):
            lon1, lat1, lon2, lat2 = line[index:index+2,].ravel()
            #print(lon1, lat1, lon2, lat2)
            #print(line[index:index+2,].ravel())
            dist += haversine(lon1, lat1, lon2, lat2)
    except Exception as e:
        #print(cont, e)
        None
    finally:
        if cont%10000 ==0: print(datetime.datetime.now(), cont)
        return round(dist,2)

In [7]:
%%time
cont=0
df['dist_perc'] = df.POLYLINE.apply(converte_dots_b)

2018-09-19 19:35:49.775357 10000
2018-09-19 19:36:07.303367 20000
2018-09-19 19:36:24.125968 30000
2018-09-19 19:36:40.843221 40000
2018-09-19 19:36:58.144834 50000
2018-09-19 19:37:15.566148 60000
2018-09-19 19:37:32.645835 70000
2018-09-19 19:37:49.565945 80000
2018-09-19 19:38:07.844749 90000
2018-09-19 19:38:24.873361 100000
2018-09-19 19:38:42.213109 110000
2018-09-19 19:38:59.124395 120000
2018-09-19 19:39:15.765232 130000
2018-09-19 19:39:32.893152 140000
2018-09-19 19:39:50.598788 150000
2018-09-19 19:40:07.462728 160000
2018-09-19 19:40:24.315280 170000
2018-09-19 19:40:41.601923 180000
2018-09-19 19:40:58.234978 190000
2018-09-19 19:41:15.115379 200000
2018-09-19 19:41:31.713562 210000
2018-09-19 19:41:48.114568 220000
2018-09-19 19:42:05.000839 230000
2018-09-19 19:42:21.754651 240000
2018-09-19 19:42:38.483545 250000
2018-09-19 19:42:55.111790 260000
2018-09-19 19:43:11.968271 270000
2018-09-19 19:43:28.469348 280000
2018-09-19 19:43:46.112508 290000
2018-09-19 19:44:04.303947 300000
2018-09-19 19:44:21.533228 310000
2018-09-19 19:44:39.001816 320000
2018-09-19 19:44:56.660978 330000
2018-09-19 19:45:12.851227 340000
2018-09-19 19:45:30.276996 350000
2018-09-19 19:45:47.913178 360000
2018-09-19 19:46:05.132621 370000
2018-09-19 19:46:21.512507 380000
2018-09-19 19:46:39.261052 390000
2018-09-19 19:46:57.284160 400000
2018-09-19 19:47:14.982382 410000
2018-09-19 19:47:32.581454 420000
2018-09-19 19:47:50.911283 430000
2018-09-19 19:48:09.512375 440000
2018-09-19 19:48:26.111748 450000
2018-09-19 19:48:43.778630 460000
2018-09-19 19:49:02.609337 470000
2018-09-19 19:49:22.348534 480000
2018-09-19 19:49:41.163664 490000
2018-09-19 19:50:01.283306 500000
2018-09-19 19:50:21.958319 510000
2018-09-19 19:50:43.378658 520000
2018-09-19 19:51:07.315189 530000
2018-09-19 19:51:29.329777 540000
2018-09-19 19:51:49.119922 550000
2018-09-19 19:52:08.141644 560000
2018-09-19 19:52:30.927524 570000
2018-09-19 19:52:52.442362 580000
2018-09-19 19:53:13.000777 590000
2018-09-19 19:53:33.699516 600000
2018-09-19 19:53:53.188349 610000
2018-09-19 19:54:10.859610 620000
2018-09-19 19:54:28.450788 630000
2018-09-19 19:54:46.516639 640000
2018-09-19 19:55:03.178568 650000
2018-09-19 19:55:20.757266 660000
2018-09-19 19:55:38.589808 670000
2018-09-19 19:55:55.368884 680000
2018-09-19 19:56:12.908551 690000
2018-09-19 19:56:30.748705 700000
2018-09-19 19:56:48.468710 710000
2018-09-19 19:57:05.356953 720000
2018-09-19 19:57:23.096280 730000
2018-09-19 19:57:41.128326 740000
2018-09-19 19:57:57.176980 750000
2018-09-19 19:58:15.737534 760000
2018-09-19 19:58:33.614098 770000
2018-09-19 19:58:50.569125 780000
2018-09-19 19:59:08.174763 790000
2018-09-19 19:59:26.965395 800000
2018-09-19 19:59:45.467048 810000
2018-09-19 20:00:02.186939 820000
2018-09-19 20:00:20.097570 830000
2018-09-19 20:00:37.376459 840000
2018-09-19 20:00:53.548214 850000
2018-09-19 20:01:11.277625 860000
2018-09-19 20:01:28.607884 870000
2018-09-19 20:01:45.217382 880000
2018-09-19 20:02:03.273517 890000
2018-09-19 20:02:21.117959 900000
2018-09-19 20:02:38.657310 910000
2018-09-19 20:02:56.085223 920000
2018-09-19 20:03:14.639891 930000
2018-09-19 20:03:31.445726 940000
2018-09-19 20:03:49.355402 950000
2018-09-19 20:04:07.184693 960000
2018-09-19 20:04:23.434111 970000
2018-09-19 20:04:41.684945 980000
2018-09-19 20:04:59.401403 990000
2018-09-19 20:05:15.836721 1000000
2018-09-19 20:05:35.266536 1010000
2018-09-19 20:05:53.311924 1020000
2018-09-19 20:06:09.136110 1030000
2018-09-19 20:06:27.081661 1040000
2018-09-19 20:06:44.693869 1050000
2018-09-19 20:07:01.586569 1060000
2018-09-19 20:07:19.324446 1070000
2018-09-19 20:07:36.695336 1080000
2018-09-19 20:07:54.243833 1090000
2018-09-19 20:08:11.373297 1100000
2018-09-19 20:08:29.440776 1110000
2018-09-19 20:08:47.380394 1120000
2018-09-19 20:09:03.881789 1130000
2018-09-19 20:09:20.335452 1140000
2018-09-19 20:09:37.842689 1150000
2018-09-19 20:09:54.922491 1160000
2018-09-19 20:10:12.713399 1170000
2018-09-19 20:10:30.383671 1180000
2018-09-19 20:10:47.313187 1190000
2018-09-19 20:11:05.131464 1200000
2018-09-19 20:11:22.782325 1210000
2018-09-19 20:11:39.383492 1220000
2018-09-19 20:11:56.811607 1230000
2018-09-19 20:12:14.512978 1240000
2018-09-19 20:12:32.052395 1250000
2018-09-19 20:12:49.000753 1260000
2018-09-19 20:13:07.302523 1270000
2018-09-19 20:13:24.921850 1280000
2018-09-19 20:13:41.530333 1290000
2018-09-19 20:13:58.663849 1300000
2018-09-19 20:14:16.947546 1310000
2018-09-19 20:14:33.599600 1320000
2018-09-19 20:14:50.879061 1330000
2018-09-19 20:15:08.095277 1340000
2018-09-19 20:15:24.272829 1350000
2018-09-19 20:15:41.290860 1360000
2018-09-19 20:15:58.930289 1370000
2018-09-19 20:16:15.040521 1380000
2018-09-19 20:16:32.790312 1390000
2018-09-19 20:16:49.610495 1400000
2018-09-19 20:17:06.850288 1410000
2018-09-19 20:17:24.009823 1420000
2018-09-19 20:17:41.489234 1430000
2018-09-19 20:17:59.408892 1440000
2018-09-19 20:18:17.396340 1450000
2018-09-19 20:18:34.538468 1460000
2018-09-19 20:18:52.506205 1470000
2018-09-19 20:19:10.287533 1480000
2018-09-19 20:19:27.590630 1490000
2018-09-19 20:19:45.521898 1500000
2018-09-19 20:20:03.600286 1510000
2018-09-19 20:20:21.210083 1520000
2018-09-19 20:20:38.167762 1530000
2018-09-19 20:20:56.447567 1540000
2018-09-19 20:21:15.217921 1550000
2018-09-19 20:21:32.079429 1560000
2018-09-19 20:21:49.649360 1570000
2018-09-19 20:22:07.268045 1580000
2018-09-19 20:22:25.468499 1590000
2018-09-19 20:22:42.838272 1600000
2018-09-19 20:22:59.735552 1610000
2018-09-19 20:23:17.336492 1620000
2018-09-19 20:23:34.629671 1630000
2018-09-19 20:23:51.487347 1640000
2018-09-19 20:24:08.982402 1650000
2018-09-19 20:24:26.515640 1660000
2018-09-19 20:24:43.198927 1670000
2018-09-19 20:25:00.368009 1680000
2018-09-19 20:25:17.797108 1690000
2018-09-19 20:25:34.956860 1700000
2018-09-19 20:25:52.268263 1710000
Wall time: 50min 21s

In [9]:
%%time
df['start'] = df.POLYLINE.apply(lambda x: ast.literal_eval(x)[0] if len(x)>2 else None)

Wall time: 20min 58s

In [10]:
%%time
df['stop'] = df.POLYLINE.apply(lambda x: ast.literal_eval(x)[-1] if len(x)>2 else None)

Wall time: 21min 1s

In [11]:
df.to_csv('train_tratado_outliers.csv', index=False, chunksize=700)

#####################